// lib/domain/entities/book.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'book.freezed.dart'; // Will be generated by Freezed

@freezed
class BookEntity with _$BookEntity {
  const factory BookEntity({
    required String id,
    required String title,
    required String author,
    required String userId, // ID of the user who posted the book
    required String condition, // e.g., 'New', 'Like New', 'Good', 'Used'
    String? imageUrl,
    String? description, // Optional: for more details
    String? swapFor, // What the user is looking to swap for
    @Default(true) bool isAvailable, // Can be set to false if swapped/deleted
    required DateTime postedDate,
  }) = _BookEntity;
}