// lib/domain/entities/message.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'message.freezed.dart'; // Will be generated by Freezed

@freezed
class MessageEntity with _$MessageEntity {
  const factory MessageEntity({
    required String id,
    required String chatId, // ID of the chat this message belongs to
    required String senderId,
    required String recipientId,
    required String content,
    required DateTime timestamp,
    @Default(false) bool isRead,
  }) = _MessageEntity;
}