// lib/domain/entities/swap.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'swap.freezed.dart'; // Will be generated by Freezed

// Enum for swap status
enum SwapStatus {
  pending('Pending'),
  accepted('Accepted'),
  rejected('Rejected'),
  completed('Completed'),
  cancelled('Cancelled');

  final String label;
  const SwapStatus(this.label);
}

@freezed
class SwapEntity with _$SwapEntity {
  const factory SwapEntity({
    required String id,
    required String bookId, // The book being offered for swap
    required String requesterUserId, // User initiating the swap
    required String ownerUserId, // User who owns the book being offered
    required SwapStatus status,
    required DateTime initiatedAt,
    DateTime? updatedAt,
    String? message, // Optional message from requester
    String? counterBookId, // If the requester offers their book in return
  }) = _SwapEntity;
}