// lib/data/models/user_model.dart
import 'package:book_swap/data/domain/entities/user.dart';
// import 'package:book_swap/domain/entities/user.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // For Timestamp

part 'user_model.freezed.dart';
part 'user_model.g.dart'; // Will be generated by json_serializable

@freezed
class UserModel with _$UserModel {
  const UserModel._(); // Private constructor for custom methods

  const factory UserModel({
    required String uid,
    required String email,
    String? displayName,
    String? photoUrl,
    @Default(false) bool isEmailVerified,
    @TimestampConverter() DateTime? createdAt, // Custom converter for DateTime <-> Timestamp
    @TimestampConverter() DateTime? lastSignInAt,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);

  // Convert Firebase User to UserModel (useful during authentication)
  factory UserModel.fromFirebaseUser(User user) {
    return UserModel(
      uid: user.uid,
      email: user.email!,
      displayName: user.displayName,
      photoUrl: user.photoURL,
      isEmailVerified: user.emailVerified,
      createdAt: user.metadata.creationTime,
      lastSignInAt: user.metadata.lastSignInTime,
    );
  }

  // Convert Firestore DocumentSnapshot to UserModel
  factory UserModel.fromDocumentSnapshot(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return UserModel.fromJson(data..['uid'] = doc.id); // Firestore document ID is the UID
  }

  // Convert UserModel to UserEntity
  UserEntity toEntity() {
    return UserEntity(
      uid: uid,
      email: email,
      displayName: displayName,
      photoUrl: photoUrl,
      isEmailVerified: isEmailVerified,
      createdAt: createdAt,
      lastSignInAt: lastSignInAt,
    );
  }
}

// Custom converter for Firestore Timestamp to DateTime
class TimestampConverter implements JsonConverter<DateTime?, Timestamp?> {
  const TimestampConverter();

  @override
  DateTime? fromJson(Timestamp? timestamp) {
    return timestamp?.toDate();
  }

  @override
  Timestamp? toJson(DateTime? date) {
    return date == null ? null : Timestamp.fromDate(date);
  }
}